//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diploma_HerminiaMarske_Noche_UAI_Lomas.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Diploma_HerminiaMarske_Noche_UAI_Lomas.Properties.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El cliente fue completamente creado..
        /// </summary>
        internal static string client_created_person_created {
            get {
                return ResourceManager.GetString("client_created_person_created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al eliminar el usuario..
        /// </summary>
        internal static string error_deleting_user {
            get {
                return ResourceManager.GetString("error_deleting_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ha ocurrido un error al modificar el usuario..
        /// </summary>
        internal static string error_modifying_user {
            get {
                return ResourceManager.GetString("error_modifying_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fallido.
        /// </summary>
        internal static string failure {
            get {
                return ResourceManager.GetString("failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mensaje.
        /// </summary>
        internal static string message {
            get {
                return ResourceManager.GetString("message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Algunos campos requeridos no fueron llenados..
        /// </summary>
        internal static string missing_info {
            get {
                return ResourceManager.GetString("missing_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor ingrese sus credenciales..
        /// </summary>
        internal static string missing_user_data {
            get {
                return ResourceManager.GetString("missing_user_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La persona no tiene domicilios..
        /// </summary>
        internal static string no_addresses {
            get {
                return ResourceManager.GetString("no_addresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La persona no tiene mails..
        /// </summary>
        internal static string no_mails {
            get {
                return ResourceManager.GetString("no_mails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La persona no tiene teléfonos..
        /// </summary>
        internal static string no_phones {
            get {
                return ResourceManager.GetString("no_phones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario no tiene familias ni patentes asignadas..
        /// </summary>
        internal static string no_profiles_nor_roles {
            get {
                return ResourceManager.GetString("no_profiles_nor_roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aceptar.
        /// </summary>
        internal static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña debe ser de al menos 6 carácteres..
        /// </summary>
        internal static string password_too_short {
            get {
                return ResourceManager.GetString("password_too_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Las contraseñas no coinciden..
        /// </summary>
        internal static string passwords_dont_match {
            get {
                return ResourceManager.GetString("passwords_dont_match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La persona ya tiene un usuario..
        /// </summary>
        internal static string person_has_user {
            get {
                return ResourceManager.GetString("person_has_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Éxito.
        /// </summary>
        internal static string success {
            get {
                return ResourceManager.GetString("success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Existe un problema con su contraseña y no se puede procesar
        ///Comuníquese con un administrador..
        /// </summary>
        internal static string user_auth_error {
            get {
                return ResourceManager.GetString("user_auth_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Contraseña incorrecta!.
        /// </summary>
        internal static string user_auth_failed {
            get {
                return ResourceManager.GetString("user_auth_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario se encuentra bloqueado
        ///Comuníquese con un administrador..
        /// </summary>
        internal static string user_blocked {
            get {
                return ResourceManager.GetString("user_blocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se creó el usuario para la persona existente..
        /// </summary>
        internal static string user_created_existing_person {
            get {
                return ResourceManager.GetString("user_created_existing_person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario y la persona fueron creados..
        /// </summary>
        internal static string user_created_person_created {
            get {
                return ResourceManager.GetString("user_created_person_created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se eliminó el usuario exitosamente..
        /// </summary>
        internal static string user_deleted {
            get {
                return ResourceManager.GetString("user_deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Este usuario ya existe..
        /// </summary>
        internal static string user_exists {
            get {
                return ResourceManager.GetString("user_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario fue modificado exitosamente..
        /// </summary>
        internal static string user_modified {
            get {
                return ResourceManager.GetString("user_modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario ingresado no existe..
        /// </summary>
        internal static string user_not_exists {
            get {
                return ResourceManager.GetString("user_not_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Bienvenido {0}!.
        /// </summary>
        internal static string welcome {
            get {
                return ResourceManager.GetString("welcome", resourceCulture);
            }
        }
    }
}
