//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diploma_HerminiaMarske_Noche_UAI_Lomas.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Diploma_HerminiaMarske_Noche_UAI_Lomas.Properties.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Avión creado con éxito..
        /// </summary>
        internal static string airplane_created {
            get {
                return ResourceManager.GetString("airplane_created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El avión fue eliminado..
        /// </summary>
        internal static string airplane_deleted {
            get {
                return ResourceManager.GetString("airplane_deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error desconocido durante el procesamiento de su solicitud..
        /// </summary>
        internal static string airplane_error {
            get {
                return ResourceManager.GetString("airplane_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Avión modificado con éxito.
        /// </summary>
        internal static string airplane_modified {
            get {
                return ResourceManager.GetString("airplane_modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se permiten carácteres especiales en este campo (ni espacios)..
        /// </summary>
        internal static string alphanumeric_only {
            get {
                return ResourceManager.GetString("alphanumeric_only", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Respaldo de base de datos|*.bak.
        /// </summary>
        internal static string backup_extensions {
            get {
                return ResourceManager.GetString("backup_extensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Respaldo en proceso, por favor espere....
        /// </summary>
        internal static string backup_in_process {
            get {
                return ResourceManager.GetString("backup_in_process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El respaldo de base de datos se realizó éxitosamente.
        /// </summary>
        internal static string backup_is_ready {
            get {
                return ResourceManager.GetString("backup_is_ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El cliente fue completamente creado..
        /// </summary>
        internal static string client_created_person_created {
            get {
                return ResourceManager.GetString("client_created_person_created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El cliente fue eliminado..
        /// </summary>
        internal static string client_deleted {
            get {
                return ResourceManager.GetString("client_deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El cliente fue modificado exitosamente..
        /// </summary>
        internal static string client_modified {
            get {
                return ResourceManager.GetString("client_modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Seguro que deseas eliminar este registro?.
        /// </summary>
        internal static string confirm_delete {
            get {
                return ResourceManager.GetString("confirm_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Deseas salir del sistema?.
        /// </summary>
        internal static string confirm_exit {
            get {
                return ResourceManager.GetString("confirm_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Deseas cerrar la sesión?.
        /// </summary>
        internal static string confirm_logout {
            get {
                return ResourceManager.GetString("confirm_logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hubo un error al validar el backup seleccionado.
        /// </summary>
        internal static string couldn_verify_backup {
            get {
                return ResourceManager.GetString("couldn_verify_backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El CUIL/CUIT debe contener 11 números (no incluya guiones)..
        /// </summary>
        internal static string cuit_format_incorrect {
            get {
                return ResourceManager.GetString("cuit_format_incorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La longitud del CUIL/CUIT debe ser 11 dígitos..
        /// </summary>
        internal static string cuit_length_incorrect {
            get {
                return ResourceManager.GetString("cuit_length_incorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡No se puede borrar el usuario en uso!.
        /// </summary>
        internal static string current_user_no_delete {
            get {
                return ResourceManager.GetString("current_user_no_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡No se puede editar al usuario en uso!.
        /// </summary>
        internal static string current_user_no_edit {
            get {
                return ResourceManager.GetString("current_user_no_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La fecha no puede ser igual a hoy (ni superior)..
        /// </summary>
        internal static string date_too_recent {
            get {
                return ResourceManager.GetString("date_too_recent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El DNI debe contener 8 números..
        /// </summary>
        internal static string dni_format_incorrect {
            get {
                return ResourceManager.GetString("dni_format_incorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La longitud del DNI debe ser 8 dígitos..
        /// </summary>
        internal static string dni_length_incorrect {
            get {
                return ResourceManager.GetString("dni_length_incorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inglés.
        /// </summary>
        internal static string english {
            get {
                return ResourceManager.GetString("english", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al eliminar el usuario..
        /// </summary>
        internal static string error_deleting_user {
            get {
                return ResourceManager.GetString("error_deleting_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ha ocurrido un error al modificar el usuario..
        /// </summary>
        internal static string error_modifying_user {
            get {
                return ResourceManager.GetString("error_modifying_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fallido.
        /// </summary>
        internal static string failure {
            get {
                return ResourceManager.GetString("failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El formato del mail debe ser &apos;nombre@dominio&apos;.
        /// </summary>
        internal static string mail_format_incorrect {
            get {
                return ResourceManager.GetString("mail_format_incorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mensaje.
        /// </summary>
        internal static string message {
            get {
                return ResourceManager.GetString("message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Algunos campos requeridos no fueron llenados..
        /// </summary>
        internal static string missing_info {
            get {
                return ResourceManager.GetString("missing_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor ingrese sus credenciales..
        /// </summary>
        internal static string missing_user_data {
            get {
                return ResourceManager.GetString("missing_user_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los nombres solo admiten texto..
        /// </summary>
        internal static string name_text_only {
            get {
                return ResourceManager.GetString("name_text_only", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La persona no tiene domicilios..
        /// </summary>
        internal static string no_addresses {
            get {
                return ResourceManager.GetString("no_addresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay conexión a la base de datos.
        /// </summary>
        internal static string no_connection_database {
            get {
                return ResourceManager.GetString("no_connection_database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No seleccionó ningún archivo.
        /// </summary>
        internal static string no_file_selected {
            get {
                return ResourceManager.GetString("no_file_selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La persona no tiene mails..
        /// </summary>
        internal static string no_mails {
            get {
                return ResourceManager.GetString("no_mails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La persona no tiene teléfonos..
        /// </summary>
        internal static string no_phones {
            get {
                return ResourceManager.GetString("no_phones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario no tiene familias ni patentes asignadas..
        /// </summary>
        internal static string no_profiles_nor_roles {
            get {
                return ResourceManager.GetString("no_profiles_nor_roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La extensión de archivo seleccionado no es válida.
        /// </summary>
        internal static string no_valid_extension {
            get {
                return ResourceManager.GetString("no_valid_extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solo se permiten números en este campo..
        /// </summary>
        internal static string numbers_only {
            get {
                return ResourceManager.GetString("numbers_only", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aceptar.
        /// </summary>
        internal static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El valor no debe ser menor a {0} ni mayor a {1}..
        /// </summary>
        internal static string out_of_range {
            get {
                return ResourceManager.GetString("out_of_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña debe ser de al menos 6 carácteres..
        /// </summary>
        internal static string password_too_short {
            get {
                return ResourceManager.GetString("password_too_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Las contraseñas no coinciden..
        /// </summary>
        internal static string passwords_dont_match {
            get {
                return ResourceManager.GetString("passwords_dont_match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La persona ya tiene un usuario..
        /// </summary>
        internal static string person_has_user {
            get {
                return ResourceManager.GetString("person_has_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El teléfono debe contener sólo números (se permite un + al inicio).
        /// </summary>
        internal static string phone_format_incorrect {
            get {
                return ResourceManager.GetString("phone_format_incorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmación requerida.
        /// </summary>
        internal static string question {
            get {
                return ResourceManager.GetString("question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recalculando dígitos verificadores.
        /// </summary>
        internal static string recalculate_in_progress {
            get {
                return ResourceManager.GetString("recalculate_in_progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recálculo completado.
        /// </summary>
        internal static string recalculation_success {
            get {
                return ResourceManager.GetString("recalculation_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recuperación en proceso, por favor espere....
        /// </summary>
        internal static string restore_in_process {
            get {
                return ResourceManager.GetString("restore_in_process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La restauración de base de datos se realizó éxitosamente.
        /// </summary>
        internal static string restore_is_ready {
            get {
                return ResourceManager.GetString("restore_is_ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione un valor de la lista desplegable..
        /// </summary>
        internal static string select_value_from_combo {
            get {
                return ResourceManager.GetString("select_value_from_combo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Español.
        /// </summary>
        internal static string spanish {
            get {
                return ResourceManager.GetString("spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El formato de la calle es incorrecto..
        /// </summary>
        internal static string street_format_incorrect {
            get {
                return ResourceManager.GetString("street_format_incorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Éxito.
        /// </summary>
        internal static string success {
            get {
                return ResourceManager.GetString("success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La longitud del campo debe ser entre {0} y {1}..
        /// </summary>
        internal static string text_length_too_short {
            get {
                return ResourceManager.GetString("text_length_too_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Existe un problema con su contraseña y no se puede procesar
        ///Comuníquese con un administrador..
        /// </summary>
        internal static string user_auth_error {
            get {
                return ResourceManager.GetString("user_auth_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Contraseña incorrecta!.
        /// </summary>
        internal static string user_auth_failed {
            get {
                return ResourceManager.GetString("user_auth_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario se encuentra bloqueado
        ///Comuníquese con un administrador..
        /// </summary>
        internal static string user_blocked {
            get {
                return ResourceManager.GetString("user_blocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se creó el usuario para la persona existente..
        /// </summary>
        internal static string user_created_existing_person {
            get {
                return ResourceManager.GetString("user_created_existing_person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario y la persona fueron creados..
        /// </summary>
        internal static string user_created_person_created {
            get {
                return ResourceManager.GetString("user_created_person_created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario fue eliminado..
        /// </summary>
        internal static string user_deleted {
            get {
                return ResourceManager.GetString("user_deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Este usuario ya existe..
        /// </summary>
        internal static string user_exists {
            get {
                return ResourceManager.GetString("user_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario fue modificado exitosamente..
        /// </summary>
        internal static string user_modified {
            get {
                return ResourceManager.GetString("user_modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario ingresado no existe..
        /// </summary>
        internal static string user_not_exists {
            get {
                return ResourceManager.GetString("user_not_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario ha sido desbloqueado.
        /// </summary>
        internal static string user_unlocked {
            get {
                return ResourceManager.GetString("user_unlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Validación terminada.
        /// </summary>
        internal static string validation_finished {
            get {
                return ResourceManager.GetString("validation_finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Validación en progreso.
        /// </summary>
        internal static string validation_in_progress {
            get {
                return ResourceManager.GetString("validation_in_progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Bienvenido {0}!.
        /// </summary>
        internal static string welcome {
            get {
                return ResourceManager.GetString("welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bienvenido/a {0}.
        /// </summary>
        internal static string welcome_user {
            get {
                return ResourceManager.GetString("welcome_user", resourceCulture);
            }
        }
    }
}
